name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]   # masterなら "master"

permissions:
  contents: read
  pages: write           # これ大事
  id-token: write        # これも大事（OIDC）

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # _site/ がリポジトリに元からあるならこのステップは不要。
      # ない場合の保険として、手元のファイルを _site に集めます。
      - name: Prepare _site
        shell: bash
        run: |
          mkdir -p _site
          [ -f index.html ] && cp -v index.html _site/
          [ -f styles.css ] && cp -v styles.css _site/
          [ -f app.js ] && cp -v app.js _site/
          [ -f image_loader.js ] && cp -v image_loader.js _site/
          [ -f image_data.csv ] && cp -v image_data.csv _site/ || true
          shopt -s nullglob
          for f in mokekelist*.txt; do cp -v "$f" _site/; done
          [ -d images ] && cp -vr images _site/
          touch _site/.nojekyll

      # ここから“正攻法”の3ステップ
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
